/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import db.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Electrodomestico;

/**
 *
 * @author Jenn
 */
public class IngresarElectrodomestico extends javax.swing.JFrame {

    /**
     * Creates new form IngresarElectrodomestico
     */
    public IngresarElectrodomestico() {
        initComponents();
        comboTipoEle.removeAllItems();
        
        comboTipoEle.addItem("");
        comboTipoEle.addItem("Lavadora");
        comboTipoEle.addItem("Microondas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTipoEle = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdDueño = new javax.swing.JTextField();
        btnGuardarElectrodomestico = new javax.swing.JButton();
        txtConfirmacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelo");

        jLabel2.setText("Marca");

        jLabel3.setText("Tipo Electrodomestico");

        jLabel4.setText("N Serie");

        comboTipoEle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoEle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoEleActionPerformed(evt);
            }
        });

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        jLabel5.setText("CC Dueño");

        btnGuardarElectrodomestico.setText("Guardar");
        btnGuardarElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarElectrodomesticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(comboTipoEle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtSerie)
                            .addComponent(txtIdDueño))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnGuardarElectrodomestico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipoEle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarElectrodomestico)
                    .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoEleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoEleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoEleActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnGuardarElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarElectrodomesticoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String aux = null;
        Conexion objConexion = new Conexion();
        if (this.txtIdDueño.getText().length() != 0 && this.txtMarca.getText().length() != 0 
                && this.txtModelo.getText().length() != 0 && this.txtSerie.getText().length() != 0 
                && !this.comboTipoEle.getSelectedItem().toString().equalsIgnoreCase("")) {
            this.txtConfirmacion.setText("guardado");
            guardarElectrodomestico();
//            try {
//            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Clientes");
//            //while para capturar el id del ultimo usuario registrado
//            while(resultado.next()){
//                    aux = resultado.getString("idCliente");
//                }
//                txtID.setText(aux);
//                txtNombre.setEditable(false);
//                txtDocumento.setEditable(false);
//                txtTelefono.setEditable(false);
//                txtDireccion.setEditable(false);
//                btnGuardarCliente.setVisible(false);
//        } catch (Exception e) {
//            System.out.println(e);
//        }
        }else{
            
            this.txtConfirmacion.setText("no guardado");
        }
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnGuardarElectrodomesticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarElectrodomestico().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarElectrodomestico;
    private javax.swing.JComboBox<String> comboTipoEle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtConfirmacion;
    private javax.swing.JTextField txtIdDueño;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    public void guardarElectrodomestico() {
        Conexion objConexion = new Conexion();
        
        Electrodomestico objElectrodomestico = recuperarDataGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO Electrodomesticos (idElectrodomestico, Tipo, Marca, Modelo, NSerie, Clientes_Documento)"
                + " VALUES (null, '%s', '%s', '%s', '%s', '%d')", objElectrodomestico.getTipo(), objElectrodomestico.getMarca(), objElectrodomestico.getModelo(), objElectrodomestico.getnSerie(), objElectrodomestico.getIdDueño() );
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        
    }
    
     private Electrodomestico recuperarDataGUI() {
        Electrodomestico objElectrodomestico = new Electrodomestico();
        
        //linea comentada era para agregar el id manualmente a la BD pero se opto por un autoincrementable
        int idCliente = (txtIdDueño.getText().isEmpty())?0: Integer.parseInt(txtIdDueño.getText()); 
        
        objElectrodomestico.setIdDueño(idCliente);
        objElectrodomestico.setTipo(comboTipoEle.getSelectedItem().toString());
        objElectrodomestico.setMarca(txtMarca.getText());
        objElectrodomestico.setModelo(txtModelo.getText());
        objElectrodomestico.setnSerie(txtSerie.getText());
        return objElectrodomestico;
    }

}
